package com.example.carteirinhadigital.core.designsystem.theme

import androidx.compose.ui.graphics.Color


// Light scheme
val PrimaryLigh = Color(0xEEFF6B6B)
val primaryLight = Color(0xEEFF5656)
val primaryContainerLight = Color(0xFFE01B1B)
val onPrimaryContainerLight = Color(0xFF000000)
val onSecondaryLight = Color(0xFF8BC34A)
val secondaryContainerLight = Color(0xFFFF7777)
val onSecondaryContainerLight = Color(0xFFFAFAFA)
val tertiaryLight = Color(0xFF775652)
val onTertiaryLight = Color(0xFF8BC34A)
val tertiaryContainerLight = Color(0xFFFF9393)
val onTertiaryContainerLight = Color(0xFF5C0010)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFBFEFF)
val errorContainerLight = Color(0xFFCDDC39)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF231A1A)
val surfaceLight = Color(0xFFD70000)
val onSurfaceLight = Color(0xFF231A1A)
val surfaceVariantLight = Color(0xFFF4DDDD)
val onSurfaceVariantLight = Color(0xFF524343)
val outlineLight = Color(0xFF857272)
val outlineVariantLight = Color(0xFFD8C1C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E2E)
val inverseOnSurfaceLight = Color(0xFFFFEDED)
val inversePrimaryLight = Color(0xFFE91E63)
val surfaceDimLight = Color(0xFFE6D6D6)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F0)
val surfaceContainerLight = Color(0xFFFFEAEA)
val surfaceContainerHighLight = Color(0xFFF9E4E4)
val surfaceContainerHighestLight = Color(0xFFF3DEDE)

// Dark scheme
val primaryDark = Color(0xFFFFB3B3)
val onPrimaryDark = Color(0xFF6B0015)
val primaryContainerDark = Color(0xFFC8102E)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFB3B5)
val onSecondaryDark = Color(0xFF68001A)
val secondaryContainerDark = Color(0xFF8B1A2A)
val onSecondaryContainerDark = Color(0xFFFFDAD9)
val tertiaryDark = Color(0xFFE7BDB8)
val onTertiaryDark = Color(0xFF442925)
val tertiaryContainerDark = Color(0xFF5D3F3B)
val onTertiaryContainerDark = Color(0xFFFFDAD6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1111)
val onBackgroundDark = Color(0xFFF3DEDE)
val surfaceDark = Color(0xFF1A1111)
val onSurfaceDark = Color(0xFFF3DEDE)
val surfaceVariantDark = Color(0xFF524343)
val onSurfaceVariantDark = Color(0xFFD8C1C1)
val outlineDark = Color(0xFFA08C8C)
val outlineVariantDark = Color(0xFF524343)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF3DEDE)
val inverseOnSurfaceDark = Color(0xFF382E2E)
val inversePrimaryDark = Color(0xFFC8102E)
val surfaceDimDark = Color(0xFF1A1111)
val surfaceBrightDark = Color(0xFF413737)
val surfaceContainerLowestDark = Color(0xFF140C0C)
val surfaceContainerLowDark = Color(0xFF231A1A)
val surfaceContainerDark = Color(0xFF271E1E)
val surfaceContainerHighDark = Color(0xFF322828)
val surfaceContainerHighestDark = Color(0xFF3D3232)
